In [4]:
import torch

In [3]:
torch.arange(0 ,10, dtype=torch.float)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [8]:
torch.arange(0 ,10, dtype=torch.float).unsqueeze(1)

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [11]:
type(10_000.0)

float

In [18]:
a = torch.rand(size=(1,2))
a

tensor([[0.6654, 0.5166]])

In [19]:
torch.exp(a)

tensor([[1.9453, 1.6764]])

In [20]:
import math

In [23]:
torch.exp(torch.arange(0, 10, 2).float() * (-math.log(10_000.0) / 10))

tensor([1.0000e+00, 1.5849e-01, 2.5119e-02, 3.9811e-03, 6.3096e-04])

In [33]:
div_term = torch.exp(
    torch.arange(0, 100, 2).float() * (-math.log(10_000.0) / 100)
)

div_term

tensor([1.0000e+00, 8.3176e-01, 6.9183e-01, 5.7544e-01, 4.7863e-01, 3.9811e-01,
        3.3113e-01, 2.7542e-01, 2.2909e-01, 1.9055e-01, 1.5849e-01, 1.3183e-01,
        1.0965e-01, 9.1201e-02, 7.5858e-02, 6.3096e-02, 5.2481e-02, 4.3652e-02,
        3.6308e-02, 3.0200e-02, 2.5119e-02, 2.0893e-02, 1.7378e-02, 1.4454e-02,
        1.2023e-02, 1.0000e-02, 8.3176e-03, 6.9183e-03, 5.7544e-03, 4.7863e-03,
        3.9811e-03, 3.3113e-03, 2.7542e-03, 2.2909e-03, 1.9055e-03, 1.5849e-03,
        1.3183e-03, 1.0965e-03, 9.1201e-04, 7.5858e-04, 6.3096e-04, 5.2481e-04,
        4.3652e-04, 3.6308e-04, 3.0200e-04, 2.5119e-04, 2.0893e-04, 1.7378e-04,
        1.4454e-04, 1.2023e-04])

In [34]:
position = torch.arange(0 ,10, dtype=torch.float).unsqueeze(1)
position

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [37]:
pe = torch.zeros(10, 100)
pe.shape

torch.Size([10, 100])

In [45]:
pe[:, 0::2] = torch.sin(position*div_term)
pe[:, 1::2] = torch.cos(position*div_term)
pe.shape

torch.Size([10, 100])

In [47]:
pe = pe.unsqueeze(0)
pe.shape

torch.Size([1, 10, 100])

In [1]:
from model import InputEmbedding, PositionalEncoding

d_model = 512

vocab_size = 10

In [11]:
input_embedding = InputEmbedding(d_model, vocab_size)

position_encoding = PositionalEncoding(512, 5, 0.5)

In [12]:
x = torch.LongTensor([1, 2, 3, 4, 5])
x

tensor([1, 2, 3, 4, 5])

In [13]:
output = input_embedding(x)

In [14]:
output.shape

torch.Size([5, 512])

In [15]:
output.shape[1]

512

In [16]:
position_encoding(output)

tensor([[[  0.0000,  -0.0000,   0.0000,  ...,   0.0000,  14.1711,  12.6049],
         [ 39.9350, -69.3352,   0.0000,  ..., -60.1059,   0.0000,   0.0000],
         [ -0.0000,  -5.1673, -19.4638,  ...,   0.0000,   0.0000,   0.0000],
         [  0.0000, -36.9313,  -0.0000,  ..., -30.0332,   0.0000,  79.7456],
         [ -0.0000,   0.0000, -59.3464,  ...,  16.3732, -47.3305, -29.8067]]],
       grad_fn=<MulBackward0>)